import type { Metadata } from 'next';
import './globals.css';
import { Noto_Sans_JP, Poppins } from 'next/font/google';

const notoSans = Noto_Sans_JP({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	variable: '--font-noto',
});

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	variable: '--font-poppins',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${notoSans.variable} ${poppins.variable} font-sans antialiased`}
		>
			<body className="font-sans">
				<header className="fixed top-0 left-0 right-0 h-16 z-50">
					<div className="flex h-16 items-center justify-between px-7">
						<nav className="mx-auto flex items-center gap-20 text-[15px]">
							<a href="#works" className="hover:opacity-60 font-poppins">
								aa
							</a>
							<a href="#services" className="hover:opacity-60 font-poppins">
								Services
							</a>
							<a href="#profile" className="hover:opacity-60 font-poppins">
								Profile
							</a>
						</nav>

						<a
							href="#contact"
							className="absolute right-7 text-[15px] text-blue-600 hover:opacity-60"
						>
							contact ↗
						</a>
					</div>
				</header>
				{children}
			</body>
		</html>
	);
}
